export const GET_SCORES = {
    START: 'GET_SCORES.START',
    FINISHED: 'GET_SCORES.FINISHED',
    FAILED: 'GET_SCORES.FAILED'
};

export const ADD_SCORE = {
    START: 'ADD_SCORE.START',
    FINISHED: 'ADD_SCORE.FINISHED',
    FAILED: 'ADD_SCORE.FAILED'
};
