export const FETCH_SCORES = {
    START: 'FETCH_SCORES.START',
    FINISHED: 'FETCH_SCORES.FINISHED',
    FAILED: 'FETCH_SCORES.FAILED'
};

export const ADD_SCORE = {
    START: 'ADD_SCORE.START',
    FINISHED: 'ADD_SCORE.FINISHED',
    FAILED: 'ADD_SCORE.FAILED'
};
